name: build-dotnet

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '5.0.301' # The .NET SDK version to use

jobs:
  build:

    name: build-win
    runs-on: windows-latest
  
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./console-app/
      
    - name: Build
      # As configuration you should choose the config you want to build. Ex. Release - Debug
      run: dotnet build ./console-app/console-app.sln --configuration release --no-restore. 
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GitHubActionsDotNetDownloadableArtifact
        path: ./console-app/console-app/bin/release/net5.0/*.*
        
    - name: End job
      run: |
        echo 'All steps ended' 
